#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# home
#   path: /
#   controller : App\Controller\HomeController::index

app_homepage:
    path: /
    controller: App\Controller\HomeController::index